/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasakhir;
import java.awt.event.KeyEvent;

/**
 *
 * @author Estu Nur Aini
 */
public class formta extends javax.swing.JFrame {

    /**
     * Creates new form formta
     */
    public formta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kolomUltah1 = new javax.swing.JComboBox<>();
        kolomUltah2 = new javax.swing.JComboBox<>();
        kolomUltah3 = new javax.swing.JComboBox<>();
        kolomNama = new javax.swing.JTextField();
        kolomGender = new javax.swing.JComboBox<>();
        kolomID = new javax.swing.JTextField();
        kolomSeat = new javax.swing.JComboBox<>();
        kolomJumlah = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        kolomTotal = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        kolomData = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        kolomInfo = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kolomUltah1.setBackground(new java.awt.Color(240, 240, 240));
        kolomUltah1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        kolomUltah1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        kolomUltah1.setBorder(null);
        kolomUltah1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(kolomUltah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 177, 40, 25));

        kolomUltah2.setBackground(new java.awt.Color(240, 240, 240));
        kolomUltah2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        kolomUltah2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Feb", "Mar", "Apr", "Mei", "Jun", "Jul", "Agu", "Sep", "Okt", "Nov", "Des" }));
        kolomUltah2.setBorder(null);
        getContentPane().add(kolomUltah2, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 177, 60, 25));

        kolomUltah3.setBackground(new java.awt.Color(240, 240, 240));
        kolomUltah3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019" }));
        kolomUltah3.setAutoscrolls(true);
        kolomUltah3.setBorder(null);
        getContentPane().add(kolomUltah3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 177, 70, 25));

        kolomNama.setBackground(new java.awt.Color(240, 240, 240));
        kolomNama.setAlignmentX(1.0F);
        kolomNama.setAlignmentY(1.0F);
        kolomNama.setBorder(null);
        kolomNama.setMargin(new java.awt.Insets(2, 4, 2, 2));
        kolomNama.setMaximumSize(new java.awt.Dimension(4, 20));
        kolomNama.setMinimumSize(new java.awt.Dimension(4, 20));
        kolomNama.setPreferredSize(new java.awt.Dimension(30, 20));
        kolomNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kolomNamaKeyTyped(evt);
            }
        });
        getContentPane().add(kolomNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 200, 25));

        kolomGender.setBackground(new java.awt.Color(240, 240, 240));
        kolomGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Perempuan", "Laki-laki" }));
        kolomGender.setSelectedItem(" ");
        kolomGender.setAlignmentX(1.0F);
        kolomGender.setAlignmentY(1.0F);
        kolomGender.setBorder(null);
        getContentPane().add(kolomGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 225, 200, 25));

        kolomID.setBackground(new java.awt.Color(240, 240, 240));
        kolomID.setAlignmentX(1.0F);
        kolomID.setAlignmentY(1.0F);
        kolomID.setBorder(null);
        kolomID.setMargin(new java.awt.Insets(2, 4, 2, 2));
        kolomID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kolomIDKeyTyped(evt);
            }
        });
        getContentPane().add(kolomID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 200, 25));

        kolomSeat.setBackground(new java.awt.Color(240, 240, 240));
        kolomSeat.setMaximumRowCount(10);
        kolomSeat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VIP", "C1", "C2", "C3", "C4", "C5" }));
        kolomSeat.setSelectedItem("Select One");
        kolomSeat.setAlignmentX(1.0F);
        kolomSeat.setAlignmentY(1.0F);
        kolomSeat.setAutoscrolls(true);
        kolomSeat.setBorder(null);
        getContentPane().add(kolomSeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 318, 200, 25));

        kolomJumlah.setBackground(new java.awt.Color(240, 240, 240));
        kolomJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolomJumlahActionPerformed(evt);
            }
        });
        kolomJumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kolomJumlahKeyTyped(evt);
            }
        });
        getContentPane().add(kolomJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 367, 50, 23));

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 70, 28));

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 70, 28));

        kolomTotal.setBackground(new java.awt.Color(240, 240, 240));
        kolomTotal.setFont(new java.awt.Font("Futura Md BT", 0, 12)); // NOI18N
        kolomTotal.setAlignmentX(1.0F);
        kolomTotal.setAlignmentY(1.0F);
        kolomTotal.setBorder(null);
        getContentPane().add(kolomTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 147, 260, 50));

        jScrollPane2.setBorder(null);
        jScrollPane2.setAlignmentX(1.0F);
        jScrollPane2.setAlignmentY(1.0F);

        kolomData.setBackground(new java.awt.Color(240, 240, 240));
        kolomData.setColumns(15);
        kolomData.setFont(new java.awt.Font("Futura Md BT", 0, 12)); // NOI18N
        kolomData.setRows(3);
        kolomData.setAlignmentX(1.0F);
        kolomData.setAlignmentY(1.0F);
        kolomData.setBorder(null);
        jScrollPane2.setViewportView(kolomData);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 270, 60));

        jScrollPane1.setBorder(null);
        jScrollPane1.setFont(new java.awt.Font("Futura Md BT", 0, 12)); // NOI18N

        kolomInfo.setBackground(new java.awt.Color(240, 240, 240));
        kolomInfo.setColumns(15);
        kolomInfo.setFont(new java.awt.Font("Futura Md BT", 0, 12)); // NOI18N
        kolomInfo.setRows(3);
        kolomInfo.setWrapStyleWord(true);
        kolomInfo.setAlignmentX(1.0F);
        kolomInfo.setAlignmentY(1.0F);
        kolomInfo.setBorder(null);
        jScrollPane1.setViewportView(kolomInfo);
        kolomInfo.getAccessibleContext().setAccessibleName("");
        kolomInfo.getAccessibleContext().setAccessibleDescription("");
        kolomInfo.getAccessibleContext().setAccessibleParent(this);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 270, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugasakhir/787.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        String nama = kolomNama.getText();
        String ID = kolomID.getText();
        Integer jumlah = Integer.parseInt(kolomJumlah.getText());
        int gender = kolomGender.getSelectedIndex();
        int seat = kolomSeat.getSelectedIndex();
        int harga = 0;
        int total = 0;
        switch(seat){
            case (0):
                harga = 2750000;
                break;
            case (1):
                harga = 2450000;
                break;
            case (2):
                harga = 1950000;
                break;
            case (3):
                harga = 1450000;
                break;
            case (4):
                harga = 950000;
                break;
            case (5):
                harga = 750000;
                break;
            }
            total = harga * jumlah;
        int tanggal = kolomUltah1.getSelectedIndex();
        int bulan = kolomUltah2.getSelectedIndex();
        int tahun = kolomUltah3.getSelectedIndex();
            kolomTotal.setText("Rp. "+total);
            kolomInfo.setText("Selamat Anda berhasil membeli tiket \ndengan seat "+kolomSeat.getItemAt(seat)+ " sebanyak "+jumlah+" tiket.");
            kolomData.setText("Nama: "+nama+" \nNo. ID: "+ID+" \nTanggal Lahir: "+kolomUltah1.getItemAt(tanggal)+" "+kolomUltah2.getItemAt(bulan)+" "+kolomUltah3.getItemAt(tahun)+" \nJenis Kelamin: "+kolomGender.getItemAt(gender));
    // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        kolomNama.setText(null);
        kolomUltah1.setSelectedItem("1");
        kolomUltah2.setSelectedItem("Jan");
        kolomUltah3.setSelectedItem("1980");
        kolomGender.setSelectedItem("Perempuan");
        kolomID.setText(null);
        kolomSeat.setSelectedItem("VIP");
        kolomJumlah.setText(null);
        kolomTotal.setText(null);
        kolomData.setText(null);
        kolomInfo.setText(null);
                // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    private void kolomJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolomJumlahActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_kolomJumlahActionPerformed

    private void kolomIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kolomIDKeyTyped
        char karakter = evt.getKeyChar();
        if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
            getToolkit().beep();
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_kolomIDKeyTyped

    private void kolomJumlahKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kolomJumlahKeyTyped
        char karakter = evt.getKeyChar();
        if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
            getToolkit().beep();
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_kolomJumlahKeyTyped

    private void kolomNamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kolomNamaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_kolomNamaKeyTyped
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea kolomData;
    private javax.swing.JComboBox<String> kolomGender;
    private javax.swing.JTextField kolomID;
    private javax.swing.JTextArea kolomInfo;
    private javax.swing.JTextField kolomJumlah;
    private javax.swing.JTextField kolomNama;
    private javax.swing.JComboBox<String> kolomSeat;
    private javax.swing.JTextField kolomTotal;
    private javax.swing.JComboBox<String> kolomUltah1;
    private javax.swing.JComboBox<String> kolomUltah2;
    private javax.swing.JComboBox<String> kolomUltah3;
    // End of variables declaration//GEN-END:variables
}
